version: '3.8'

services:
  megabot:
    build: .
    container_name: mega-downloader-bot
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Optional: You can uncomment the line below if you want to inspect downloaded 
      # files on your host machine before the bot deletes them. 
      # Otherwise, it runs faster using the container's internal storage.
      # - ./downloads:/app/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
